\*Please Run in colab

# Setup

### Environment Setup

In [1]:
!pip install instructor

Requirement already satisfied: instructor in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from instructor) (3.13.2)
Requirement already satisfied: diskcache>=5.6.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (5.6.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor) (3.1.6)
Requirement already satisfied: jiter<0.12,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.11.1)
Requirement already satisfied: openai<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.8.1)
Requirement already satisfied: pre-commit>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (4.5.0)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.41.4)
Requirement already satisfied: pydantic<3.0.0,>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.12.3)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.32.4)
Requirement already satisfied: rich<15.0.0,>=13.7.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (13.9.4)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (9.1.2)
Requirement already satisfied: ty>=0.0.1a23 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.0.1a28)
Requirement already satisfied: typer<1.0.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.20.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.22.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (0.28.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.15.0)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (3.5.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (2.6.15)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (6.0.3)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (20.35.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.8.0->instructor) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.8.0->instructor) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.7.0->instructor) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.7.0->instructor) (2.19.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9.0->instructor) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9.0->instructor) (1.5.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.0.0->instructor) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.0.0->instructor) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.7.0->instructor) (0.1.2)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (0.4.0)
Requirement already satisfied: filelock<4,>=3.12.2 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (3.20.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (4.5.0)

In [2]:
# !cp /content/macro_financial_forecasting/applications/macro_financial_forecasting/data/danidanou_Bloomberg_Financial_News_train /content/
!cd /content
!rm -rf macro_financial_forecasting

In [3]:
!git clone https://github.com/chuanbinp/macro_financial_forecasting.git

Cloning into 'macro_financial_forecasting'...
remote: Enumerating objects: 1913, done.
remote: Counting objects: 100% (620/620), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 1913 (delta 475), reused 443 (delta 438), pack-reused 1293 (from 2)
Receiving objects: 100% (1913/1913), 39.56 MiB | 14.56 MiB/s, done.
Resolving deltas: 100% (1218/1218), done.

In [4]:
# !cp /content/danidanou_Bloomberg_Financial_News_train /content/macro_financial_forecasting/applications/macro_financial_forecasting/data/danidanou_Bloomberg_Financial_News_train

In [5]:
%cd macro_financial_forecasting/applications/macro_financial_forecasting/src

/content/macro_financial_forecasting/applications/macro_financial_forecasting/src

### Mount GDrive

In [6]:
from google.colab import drive

# This will prompt you to authorize Colab to access your Google Drive.
drive.mount('/content/gdrive')
GDRIVE_PATH = "/content/gdrive/MyDrive/macro_financial_forecasting_files/"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

### Code Setup

In [7]:
from config import Config
from train_data_loader import TrainDataLoader
from data_model.bloomberg_news_entry import BloombergNewsEntry
from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
config = Config("../config.env")

train_data_loader = TrainDataLoader(config)

# Train Data Loader

In [8]:
print("Starting loading pipeline ...")
print(f"Config: {config}")

train_ds = train_data_loader.load()
print("Loading pipeline completed.")

Starting loading pipeline ...
Config: Config(
  gemini_api_key: !secret!
  openai_api_key: !secret!
  llm_model: openai/gpt-5-nano-2025-08-07
  industries: ['Information Technology', 'Health Care', 'Financials', 'Consumer Discretionary', 'Communication Services', 'Industrials', 'Consumer Staples', 'Energy', 'Utilities', 'Real Estate', 'Materials', 'General Market', 'None']
  dataset_name: danidanou/Bloomberg_Financial_News
  dataset_dir: ../data/
  rss_feeds: ['https://feeds.bloomberg.com/news/news.rss', 'https://feeds.bloomberg.com/markets/news.rss', 'https://feeds.bloomberg.com/business/news.rss', 'https://feeds.bloomberg.com/technology/news.rss', 'https://feeds.bloomberg.com/politics/news.rss', 'https://feeds.bloomberg.com/wealth/news.rss', 'https://feeds.bloomberg.com/economics/news.rss', 'https://feeds.bloomberg.com/green/news.rss', 'https://feeds.bloomberg.com/pursuits/news.rss', 'https://feeds.bloomberg.com/opinion/news.rss', 'https://feeds.bloomberg.com/finance/news.rss', 'https://feeds.bloomberg.com/real-estate/news.rss', 'https://feeds.bloomberg.com/deals/news.rss', 'https://feeds.bloomberg.com/crypto/news.rss', 'https://feeds.bloomberg.com/europe/news.rss', 'https://feeds.bloomberg.com/uk/news.rss', 'https://feeds.bloomberg.com/asia/news.rss', 'https://feeds.bloomberg.com/commodities/news.rss', 'https://feeds.bloomberg.com/currencies/news.rss', 'https://feeds.bloomberg.com/fixed-income/news.rss', 'https://feeds.bloomberg.com/equities/news.rss', 'https://feeds.bloomberg.com/etfs/news.rss']
  prompt_instructions: You are a financial news analyst.
Think about how the news article impacts financial markets, especi... (truncated)
)
Downloading dataset 'danidanou/Bloomberg_Financial_News' with split 'train' from the Hugging Face Hub...

bloomberg_financial_data.parquet.gzip:   0%|          | 0.00/482M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/446762 [00:00<?, ? examples/s]

--- Download Successful! ---

Map:   0%|          | 0/446762 [00:00<?, ? examples/s]

Training dataset processed.

--- Starting validation of 446762 entries ---

Validating entries: 100%|██████████| 446762/446762 [00:29<00:00, 15003.55it/s]

--- Validation Complete! ---
Training dataset validated.
Saving processed dataset to local cache at '../data/danidanou_Bloomberg_Financial_News_train'...
Total number of rows: 446762
Loading pipeline completed.

# Data Processing Pipeline

Update these 2 variable to specify which indices to process.

In [9]:
DATA_START=0
DATA_END=100

In [10]:
from processor import NewsProcessor
import nest_asyncio
nest_asyncio.apply()

processor = NewsProcessor(config)
train_ds = processor.remove_redundant_info(train_ds[DATA_START:DATA_END])
df = processor.enrich_news_entries_with_classifications(train_ds, save_path=f"{GDRIVE_PATH}processed_news") #Sample size
df = processor.group_by_date_and_industry(df, save_path=f"{GDRIVE_PATH}grouped_news")
df = processor.filter_and_analyze_news(df)
df = processor.extract_impactful_news(df, top_n=3, save_path=f"{GDRIVE_PATH}impact_news")
df = processor.get_consolidated_sentiment(df, save_path=f"{GDRIVE_PATH}sentiment_news")

Device set to use cuda:0

Processing 100 news entries...

FinBERT Sentiment: 100%|██████████| 1/1 [00:00<00:00,  1.17batch/s]
Industry Classification: 100%|██████████| 4/4 [00:05<00:00,  1.38s/batch]

Completed processing 100 entries

============================================================
Dropped 2 (Industry, Date) pairs with Industry='None'
Remaining pairs: 19
============================================================

Summary Statistics:
Total unique (Industry, Date) pairs: 19
Average articles per pair: 5.11
Max articles in a pair: 51
Min articles in a pair: 1
25th percentile: 1.0
50th percentile: 2.0
75th percentile: 4.5
Number of pairs with at least 3 articles: 6
Total articles: 97

============================================================

Extracting top 3 impactful news per (Industry, Date) pair...

Processing groups: 100%|██████████| 19/19 [00:00<00:00, 44846.24it/s]

Processing 19 news entries...

FinBERT Sentiment: 100%|██████████| 1/1 [00:00<00:00,  7.44batch/s]

Completed processing 19 entries

In [11]:
df = await processor.get_explanation(df, save_path=f"{GDRIVE_PATH}sentiment_news")

Explanation: 100%|██████████| 19/19 [00:18<00:00,  1.04it/s]

In [12]:
df

,Industry,Date,News,ArticleCount,ImpactfulNews,AvgSentimentScore,SentimentScore,SentimentExplanation
0,Communication Services,2011-10-06,[{'Headline': 'FCC to Revamp Phone Subsidy to ...,2,[{'Headline': 'Euro-Area Leaders to Hold Summi...,0.709191,-0.291917,Overall sentiment for the Communications Servi...
1,Consumer Discretionary,2011-10-06,[{'Headline': 'PepsiCo May Purchase Russian Dr...,1,[{'Headline': 'PepsiCo May Purchase Russian Dr...,0.881740,0.888237,The article’s sentiment is strongly positive f...
2,Consumer Staples,2011-10-06,[{'Headline': 'Ukraine’s Grain Harvest Advance...,1,[{'Headline': 'Ukraine’s Grain Harvest Advance...,-0.918589,-0.917441,Explanation: FinBERT indicates a strongly nega...
3,Energy,2011-10-06,[{'Headline': 'Clean-Tech Companies Should Get...,9,[{'Headline': 'Norway Boosts Mongstad Carbon-S...,0.252093,-0.252850,"The energy-angle sentiment is mildly negative,..."
4,Financials,2011-10-06,[{'Headline': 'Ivory Coast Keeps Cocoa Export ...,51,[{'Headline': 'Remittances to Vietnam Thru Jul...,-0.306989,-0.032282,Combined FinBERT signal for the Financials set...
5,General Market,2011-10-06,[{'Headline': 'Farmland Seen Returning Up to 1...,4,[{'Headline': 'GE Study Finds Recession’s Job ...,-0.256293,-0.873807,Overall sentiment is negative: the combined Fi...
6,Health Care,2011-10-06,[{'Headline': 'House Panel Seeks Details on IR...,2,[{'Headline': 'Emdeon Said to Set Rate on $1.2...,0.666714,0.682417,Score: +0.67. Explanation: The Health Care new...
7,Industrials,2011-10-06,[{'Headline': 'Airbus German Workers Plan Work...,5,"[{'Headline': 'Polish Stocks: Getin, KGHM, Lot...",-0.296801,-0.868415,Explanation: The Industrials sentiment is nega...
8,Information Technology,2011-10-06,[{'Headline': 'Fans Hold IPhone-Lit Vigils for...,2,[{'Headline': 'Fans Hold IPhone-Lit Vigils for...,0.412332,0.002113,Net sentiment for the Information Technology t...
9,Materials,2011-10-06,[{'Headline': 'USDA Boxed Beef Cutout Closing ...,5,[{'Headline': 'Ukraine September Consumer Pric...,0.853697,0.875244,Combined materials-focused sentiment is strong...
10,Real Estate,2011-10-06,[{'Headline': 'U.S. Apartment Vacancies Drop t...,6,[{'Headline': 'Australian Homes for Sale Jump ...,-0.315012,-0.884678,The overall signal for Real Estate is modestly...
11,Utilities,2011-10-06,[{'Headline': 'Bulgaria Files $81 Million Arbi...,1,[{'Headline': 'Bulgaria Files $81 Million Arbi...,0.132956,0.135895,Explanation: The article scores mildly positiv...
12,Financials,2011-10-07,[{'Headline': 'Hana Financial Pushes for Korea...,2,[{'Headline': 'Investors Pull $113 Million Fro...,0.193224,0.010401,The combined FinBERT score for the Financials ...
13,Industrials,2011-10-07,[{'Headline': 'Doctor Accused of Aiding Bin La...,1,[{'Headline': 'Doctor Accused of Aiding Bin La...,0.149895,0.161152,The combined FinBERT score of about +0.15 sign...
14,Information Technology,2011-10-07,[{'Headline': 'Samsung Profit Beats Estimates ...,1,[{'Headline': 'Samsung Profit Beats Estimates ...,-0.914339,-0.915251,Samsung beat profit estimates thanks to smartp...
15,Real Estate,2011-10-07,[{'Headline': 'Irish Trophy Home Plunges 75% i...,1,[{'Headline': 'Irish Trophy Home Plunges 75% i...,0.013776,0.014904,The sentiment is near neutral (approximately +...
16,Communication Services,2011-10-13,[{'Headline': 'South Africa Daybook: Mining Ou...,1,[{'Headline': 'South Africa Daybook: Mining Ou...,0.017970,0.015964,The article carries a very small positive sent...
17,Financials,2011-10-21,[{'Headline': 'Kelusa Capital China Seeks Mone...,1,[{'Headline': 'Kelusa Capital China Seeks Mone...,0.271526,0.275731,The article yields a mildly positive sentiment...
18,Consumer Staples,2011-10-23,[{'Headline': 'Major League Baseball’s Postsea...,1,[{'Headline': 'Major League Baseball’s Postsea...,0.878062,0.877797,The FinBERT score of +0.878 indicates very bul...

In [13]:
import pandas as pd
pd.read_parquet(f"{GDRIVE_PATH}sentiment_news")

,Industry,Date,News,ArticleCount,ImpactfulNews,AvgSentimentScore,SentimentScore,SentimentExplanation
0,Communication Services,2011-10-06,[{'Article': 'U.S. regulators proposed overhau...,2,[{'Article': 'Euro-area government leaders wil...,0.709191,-0.291917,Overall sentiment for the Communications Servi...
1,Consumer Discretionary,2011-10-06,[{'Article': 'PepsiCo Inc. is in talks to buy ...,1,[{'Article': 'PepsiCo Inc. is in talks to buy ...,0.881740,0.888237,The article’s sentiment is strongly positive f...
2,Consumer Staples,2011-10-06,[{'Article': 'Ukraine’s grain harvest rose by ...,1,[{'Article': 'Ukraine’s grain harvest rose by ...,-0.918589,-0.917441,Explanation: FinBERT indicates a strongly nega...
3,Energy,2011-10-06,"[{'Article': 'Reed Hundt, head of the Coalitio...",9,[{'Article': 'Norway revised the cost estimate...,0.252093,-0.252850,"The energy-angle sentiment is mildly negative,..."
4,Financials,2011-10-06,[{'Article': 'Export taxes on cocoa beans from...,51,[{'Article': 'Remittances to Vietnam in the Ja...,-0.306989,-0.032282,Combined FinBERT signal for the Financials set...
5,General Market,2011-10-06,[{'Article': 'Farmland investments may return ...,4,[{'Article': 'Midsized U.S. companies that add...,-0.256293,-0.873807,Overall sentiment is negative: the combined Fi...
6,Health Care,2011-10-06,"[{'Article': 'Representative Charles Boustany,...",2,"[{'Article': 'Emdeon Inc. (EM) , the provider ...",0.666714,0.682417,Score: +0.67. Explanation: The Health Care new...
7,Industrials,2011-10-06,[{'Article': 'Airbus SAS labor unions in Germa...,5,[{'Article': 'Poland ’s WIG20 Index advanced f...,-0.296801,-0.868415,Explanation: The Industrials sentiment is nega...
8,Information Technology,2011-10-06,[{'Article': 'Apple Inc. (AAPL) fans worldwide...,2,[{'Article': 'Apple Inc. (AAPL) fans worldwide...,0.412332,0.002113,Net sentiment for the Information Technology t...
9,Materials,2011-10-06,[{'Article': 'October 6 (Bloomberg) -- This ta...,5,[{'Article': 'Following is a table detailing S...,0.853697,0.875244,Combined materials-focused sentiment is strong...
10,Real Estate,2011-10-06,[{'Article': 'U.S. apartment vacancies fell to...,6,[{'Article': 'Australian properties listed for...,-0.315012,-0.884678,The overall signal for Real Estate is modestly...
11,Utilities,2011-10-06,[{'Article': 'Bulgaria filed a 61 million-euro...,1,[{'Article': 'Bulgaria filed a 61 million-euro...,0.132956,0.135895,Explanation: The article scores mildly positiv...
12,Financials,2011-10-07,[{'Article': 'Hana Financial Group Inc. (08679...,2,[{'Article': '(Corrects starting in headline t...,0.193224,0.010401,The combined FinBERT score for the Financials ...
13,Industrials,2011-10-07,[{'Article': 'A Pakistani commission’s recomme...,1,[{'Article': 'A Pakistani commission’s recomme...,0.149895,0.161152,The combined FinBERT score of about +0.15 sign...
14,Information Technology,2011-10-07,"[{'Article': 'Samsung Electronics Co., the wor...",1,"[{'Article': 'Samsung Electronics Co., the wor...",-0.914339,-0.915251,Samsung beat profit estimates thanks to smartp...
15,Real Estate,2011-10-07,[{'Article': 'A six-bedroom Edwardian house on...,1,[{'Article': 'A six-bedroom Edwardian house on...,0.013776,0.014904,The sentiment is near neutral (approximately +...
16,Communication Services,2011-10-13,[{'Article': 'Statistics South Africa will rel...,1,[{'Article': 'Statistics South Africa will rel...,0.017970,0.015964,The article carries a very small positive sent...
17,Financials,2011-10-21,[{'Article': '(Corrects to clarify that the fu...,1,[{'Article': '(Corrects to clarify that the fu...,0.271526,0.275731,The article yields a mildly positive sentiment...
18,Consumer Staples,2011-10-23,[{'Article': 'Major League Baseball ’s postsea...,1,[{'Article': 'Major League Baseball ’s postsea...,0.878062,0.877797,The FinBERT score of +0.878 indicates very bul...